name: anndatar_example
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - pip
  - pip:
      - anndata==0.11.4
      - scanpy==1.11.4
      - numpy==2.2.6
      - pandas==2.3.0
      - scipy==1.14.1
      - zarr==2.18.7
      - igraph==1.0.0
      - leiden==0.11.0